//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmaLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowedMode {
            get {
                return ((string)(this["WindowedMode"]));
            }
            set {
                this["WindowedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GlobalAutoMatchClientMod {
            get {
                return ((string)(this["GlobalAutoMatchClientMod"]));
            }
            set {
                this["GlobalAutoMatchClientMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CloseLauncherApp {
            get {
                return ((string)(this["CloseLauncherApp"]));
            }
            set {
                this["CloseLauncherApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2LaunchParams {
            get {
                return ((string)(this["Arma2LaunchParams"]));
            }
            set {
                this["Arma2LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2Path {
            get {
                return ((string)(this["Arma2Path"]));
            }
            set {
                this["Arma2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2OAPath {
            get {
                return ((string)(this["Arma2OAPath"]));
            }
            set {
                this["Arma2OAPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3Path {
            get {
                return ((string)(this["Arma3Path"]));
            }
            set {
                this["Arma3Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DebugModeDoNotLaunchGame {
            get {
                return ((string)(this["DebugModeDoNotLaunchGame"]));
            }
            set {
                this["DebugModeDoNotLaunchGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3LaunchParams {
            get {
                return ((string)(this["Arma3LaunchParams"]));
            }
            set {
                this["Arma3LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeArma2PathInArma3LaunchParams {
            get {
                return ((string)(this["IncludeArma2PathInArma3LaunchParams"]));
            }
            set {
                this["IncludeArma2PathInArma3LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeArma2OAPathInArma3LaunchParams {
            get {
                return ((string)(this["IncludeArma2OAPathInArma3LaunchParams"]));
            }
            set {
                this["IncludeArma2OAPathInArma3LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeAdditionalArmaPaths1InArma3LaunchParams {
            get {
                return ((string)(this["IncludeAdditionalArmaPaths1InArma3LaunchParams"]));
            }
            set {
                this["IncludeAdditionalArmaPaths1InArma3LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2OAExe {
            get {
                return ((string)(this["Arma2OAExe"]));
            }
            set {
                this["Arma2OAExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalArmaPaths2 {
            get {
                return ((string)(this["AdditionalArmaPaths2"]));
            }
            set {
                this["AdditionalArmaPaths2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeAddtionalArmaPaths1InArma2LaunchParams {
            get {
                return ((string)(this["IncludeAddtionalArmaPaths1InArma2LaunchParams"]));
            }
            set {
                this["IncludeAddtionalArmaPaths1InArma2LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalArmaPaths1 {
            get {
                return ((string)(this["AdditionalArmaPaths1"]));
            }
            set {
                this["AdditionalArmaPaths1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeAdditionalArmaPaths2InArma2LaunchParams {
            get {
                return ((string)(this["IncludeAdditionalArmaPaths2InArma2LaunchParams"]));
            }
            set {
                this["IncludeAdditionalArmaPaths2InArma2LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeAdditionalArmaPaths2InArma3LaunchParams {
            get {
                return ((string)(this["IncludeAdditionalArmaPaths2InArma3LaunchParams"]));
            }
            set {
                this["IncludeAdditionalArmaPaths2InArma3LaunchParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3Exe {
            get {
                return ((string)(this["Arma3Exe"]));
            }
            set {
                this["Arma3Exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2SupportedModList {
            get {
                return ((string)(this["Arma2SupportedModList"]));
            }
            set {
                this["Arma2SupportedModList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppNotes {
            get {
                return ((string)(this["AppNotes"]));
            }
            set {
                this["AppNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RefreshExtended {
            get {
                return ((string)(this["RefreshExtended"]));
            }
            set {
                this["RefreshExtended"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppWidth {
            get {
                return ((string)(this["AppWidth"]));
            }
            set {
                this["AppWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppHeight {
            get {
                return ((string)(this["AppHeight"]));
            }
            set {
                this["AppHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppTop {
            get {
                return ((string)(this["AppTop"]));
            }
            set {
                this["AppTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppLeft {
            get {
                return ((string)(this["AppLeft"]));
            }
            set {
                this["AppLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppStateMaximized {
            get {
                return ((string)(this["AppStateMaximized"]));
            }
            set {
                this["AppStateMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DebugModeTestLocalOnly {
            get {
                return ((string)(this["DebugModeTestLocalOnly"]));
            }
            set {
                this["DebugModeTestLocalOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaxPing {
            get {
                return ((string)(this["MaxPing"]));
            }
            set {
                this["MaxPing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedGameType {
            get {
                return ((string)(this["SelectedGameType"]));
            }
            set {
                this["SelectedGameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3ExeParams {
            get {
                return ((string)(this["Arma3ExeParams"]));
            }
            set {
                this["Arma3ExeParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3ModParams {
            get {
                return ((string)(this["Arma3ModParams"]));
            }
            set {
                this["Arma3ModParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma3ExtraParams {
            get {
                return ((string)(this["Arma3ExtraParams"]));
            }
            set {
                this["Arma3ExtraParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2OAExeParams {
            get {
                return ((string)(this["Arma2OAExeParams"]));
            }
            set {
                this["Arma2OAExeParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2ModParams {
            get {
                return ((string)(this["Arma2ModParams"]));
            }
            set {
                this["Arma2ModParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arma2ExtraParams {
            get {
                return ((string)(this["Arma2ExtraParams"]));
            }
            set {
                this["Arma2ExtraParams"] = value;
            }
        }
    }
}
